base_url: /
title: roguelynn
author: roguelynn
domain: www.roguelynn.com
date_format: "%B %d, %Y"
posts_url: /words/<title>/
social:
    github: econchick
    twitter: roguelynn
jinja:
    extensions:
        - jinja2.ext.loopcontrols
misaka:
    render_flags:
        toc: true
tag_layout: tag.html
tags_url: /category/