base_url: /
title: roguelynn
author: roguelynn
domain: www.roguelynn.com
date_format: "%B %d, %Y"
posts_url: /words/<slug>/
social:
    github: econchick
    twitter: roguelynn
jinja:
    extensions:
        - jinja2.ext.loopcontrols
hoep:
    render_flags:
        toc: true
containers:
    talks:
        url: /talks/<slug>/
    projects:
        url: /projects/<slug>/
    resume:
        url: /resume/
    drafts:
        url: /~drafts/
